import { randomBytes } from "node:crypto";

/**
 * Git flow helpers - prepare branch/commit metadata for later use.
 * Actual git operations will be handled by extension when presenting results.
 */
export interface GitFlowMetadata {
  branchName: string;
  commitMessage: string;
  authorName: string;
  authorEmail: string;
}

export function generateGitFlow(task: string, authorName: string, authorEmail: string): GitFlowMetadata {
  // Generate kebab-case branch name from task
  const branchBase = task
    .toLowerCase()
    .slice(0, 40)
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const branchSuffix = randomBytes(3).toString("hex");
  const branchName = `vibecoder/${branchBase}-${branchSuffix}`;

  const commitMessage = `feat(vibecoder): ${task.slice(0, 60)}

Generated by VibeCoder MVP
Pipeline: planner -> coder -> reviewer`;

  return {
    branchName,
    commitMessage,
    authorName,
    authorEmail
  };
}
